SET ECHO ON 
DROP TABLE Sailors CASCADE CONSTRAINTS;
DROP TABLE Boats CASCADE CONSTRAINTS;
DROP TABLE Reservations CASCADE CONSTRAINTS;
DROP VIEW LazySailors;
SET ECHO OFF
SELECT * FROM USER_TABLES;
SELECT * FROM USER_VIEWS; 